# Generated by Django 4.1.2 on 2022-10-23 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=7)),
                ('companies', models.CharField(max_length=15)),
                ('comments', models.CharField(max_length=100)),
                ('money', models.DecimalField(decimal_places=10, max_digits=11, max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['date'], name='Companies_date_time_idx'),
        ),
    ]
