# Generated by Django 4.1.2 on 2022-10-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('obj', models.CharField(max_length=10, verbose_name='model')),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'posts_logs',
            },
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['datetime'], name='datetime_index'),
        ),
    ]
